name: reviewdog

on:
  pull_request:
    types: [opened, synchronize]

env:
  VIEW_ROOT: ./app

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          workdir: ${{ env.VIEW_ROOT }}
          eslint_flags: './**/*.{vue,ts,tsx,js}'

  stylelint:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: stylelint review
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          workdir: ${{ env.VIEW_ROOT }}
          stylelint_input: './**/*.{vue,css,scss}'
