name: reviewdog

on:
  pull_request:
    types: [opened, synchronize]

env:
  VIEW_ROOT: ./app

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # - name: cache dependencies
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.cache/yarn
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      # - name: install dependencies
      #   working-directory: ${{ env.VIEW_ROOT }}
      #   run: yarn install --frozen-lockfile

      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          workdir: ${{ env.VIEW_ROOT }}
          eslint_flags: './**/*.{vue,ts,tsx,js}'

      # - name: lint check
      #   working-directory: ${{ env.VIEW_ROOT }}
      #   run: yarn lint

  stylelint:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: stylelint review
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          workdir: ${{ env.VIEW_ROOT }}
          stylelint_input: './**/*.{vue,css,scss}'
