name: reviewdog

on:
  pull_request:
    types: [opened, synchronize]

env:
  VIEW_ROOT: ./app

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          workdir: ${{ env.VIEW_ROOT }}
          eslint_flags: './**/*.{vue,ts,tsx,js}'

      - name: stylelint review
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          stylelint_config: 'stylelint-config-recommended'
          stylelint_input: './**/*.{vue,css,scss}'
